name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 8 * * 5'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
          - java: 11
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: sbt -v scalafmtCheckAll scalafmtSbtCheck assembly
