name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 8 * * 5'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 8
          - java: 11
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c # v3.8.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: sbt -v scalafmtCheckAll scalafmtSbtCheck assembly
